### ISSUE TITLE
Merge files issue when delete on top of file

### ISSUE THREAD

**Issue by v-bilous** [v-bilous/difhub-codegen#43]
When a new version of the file deletes rows on the top – the is no effect on the destination:

example to reproduce 
existing file:
```
spring:
  profiles:
    active: security
authorization:
  token-url: https://local/keycloak/v1/auth/realms/client/protocol/openid-connect/token
```
new file (from codegen)
```
authorization:
  token-url: https://local/keycloak/v1/auth/realms/client/protocol/openid-connect/token
```
